[project]
name = "demo-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.9.4",
    "dbt-postgres>=1.9.0",
    "psycopg2-binary>=2.9.10",
]
