version: 2

sources:
  - name: dbt_demo
    database: "{{ env_var('POSTGRES_DBNAME') }}"
    schema: "{{ env_var('POSTGRES_SCHEMA') }}"
    tables:
      - name: customers
        description: Raw customer data
      - name: orders
        description: Raw order data
      - name: products
        description: Raw product data
      - name: employees
        description: Raw employee data 